language: php

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - ./vendor/bin/phpunit tests --coverage-php build/logs/php_$(php -r 'echo phpversion();').cov

after_script:
  - ./vendor/phpunit/phpcov/phpcov merge --clover build/logs/clover.xml build/logs
  - travis_retry php vendor/bin/coveralls -v