language: php

install:
  - curl -s http://getcomposer.org/installer | php
  - php -r 'echo ini_get("memory_limit") . "\n";'
  - php composer.phar config -g github-protocols https
  - travis_wait php -d memory_limit=2G -dzend_extension=xdebug.so composer.phar install --dev --prefer-dist --profile
  - mkdir -p build/logs

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - ./vendor/bin/phpunit tests --coverage-clover ./build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry php vendor/bin/codacycoverage clover ./build/logs/clover.xml
