language: php

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - ./vendor/bin/phpunit tests

after_script:
  - travis_retry php vendor/bin/coveralls -v